# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - muschellij2/oro.nifti
  - muschellij2/fslr

notifications:
  email:
    on_success: change
    on_failure: change
